- name: This playbook will install nginx web server, configures it and deploy a web page in it.
  hosts: all
  gather_facts: yes 
  vars:
    - greeting_msg: DevOps!
    - cm_tool: Ansible
    - provisioner_tool: Docker
  tasks:
    - name: Install nginx web server in Ubuntu
      when: ( ansible_distribution == "Ubuntu" and ansible_os_family == "Debian" )
      apt: name=nginx state=latest update_cache=yes

    - name: Install Extra Packages For Enterprise Linux (EPEL) in CentOS 
      when: ( ansible_distribution == "CentOS" and ansible_os_family == "RedHat" )
      yum: name=epel-release state=latest 

    - name: Install nginx web server in CentOS 
      when: ( ansible_distribution == "CentOS" and ansible_os_family == "RedHat" )
      yum: name=nginx state=latest 

    - name: Configure nginx document root folder in Ubuntu
      when: ( ansible_distribution == "Ubuntu" and ansible_os_family == "Debian" )
      copy: src=default dest=/etc/nginx/sites-available/default backup=yes

    - name: Configure nginx document root folder in CentOS 
      when: ( ansible_distribution == "CentOS" and ansible_os_family == "RedHat" )
      copy: src=default.conf dest=/etc/nginx/conf.d/default.conf backup=yes

    - name: Create the nginx document root folder
      file: path=/var/html state=directory mode=0777

    - name: Restart the nginx web server to apply the config changes 
      command: service nginx restart

    - name: Deploy a custom web page inside nginx web server
      template: src=index.html.j2 dest=/var/html/index.html
