- name: Demonstrates use of docker_container module and practical usecase for sequence
  hosts: localhost
  tasks:
   - name: Install pip in CentOS
     when: ansible_distribution == "CentOS"
     yum: name=python-pip state=latest

   - name: Install pip in Ubuntu 
     when: ansible_distribution == "Ubuntu"
     apt: name=python-pip state=latest update_cache=yes

   - name: Install docker-py python module
     shell: pip install docker-py

   - name: Proivision ubuntu containers
     docker_container:
         name: "ubuntu{{item}}"
         image: "tektutor/ansible-ubuntu"
         state: "started"
         ports:
           - "200{{item}}:22"
           - "800{{item}}:80"
     with_sequence: start=1 end=5

   - name: Proivision centos containers
     docker_container:
         name: "centos{{item}}"
         image: "tektutor/ansible-centos"
         state: "started"
         ports:
           - "300{{item}}:22"
           - "900{{item}}:80"
     with_sequence: start=1 end=5
